// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace School_Management_System.Models;

[Table("Class")]
public partial class Class
{
    [Key]
    public int ClassID { get; set; }

    [StringLength(30)]
    public string Name { get; set; }

    public int? GradeLevel { get; set; }

    public int? TeacherID { get; set; }

    [InverseProperty("Class")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    [ForeignKey("TeacherID")]
    [InverseProperty("Classes")]
    public virtual Teacher Teacher { get; set; }
}