// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace School_Management_System.Models;

[Table("Course")]
public partial class Course
{
    [Key]
    public int CourseID { get; set; }

    [StringLength(30)]
    public string Name { get; set; }

    [StringLength(50)]
    public string Description { get; set; }

    public int? TeacherID { get; set; }

    public int? DepartmentID { get; set; }

    [ForeignKey("DepartmentID")]
    [InverseProperty("Courses")]
    public virtual Department Department { get; set; }

    [InverseProperty("Course")]
    public virtual ICollection<Enrollment> Enrollments { get; set; } = new List<Enrollment>();

    [InverseProperty("Course")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    [ForeignKey("TeacherID")]
    [InverseProperty("Courses")]
    public virtual Teacher Teacher { get; set; }
}