// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
namespace School_Management_System.Models;

[Table("Course")]
public partial class Course
{
    [Key]
    public int CourseID { get; set; }

    [Required(ErrorMessage = "Course name is required")]
    [StringLength(30, MinimumLength = 3, ErrorMessage = "Course name must be between 3 and 100 characters")] 
    public string Name { get; set; }

    [Required(ErrorMessage = "Description is required")]
    [StringLength(100)]
    public string Description { get; set; }

    [Required(ErrorMessage = "You must assign a teacher")]
    public int? TeacherID { get; set; }
    [Required(ErrorMessage = "You must choose a department")]
    public int? DepartmentID { get; set; }

    [ForeignKey("DepartmentID")]
    [InverseProperty("Courses")]
    public virtual Department Department { get; set; }

    [InverseProperty("Course")]
    public virtual ICollection<Enrollment> Enrollments { get; set; } = new List<Enrollment>();

    [InverseProperty("Course")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    [ForeignKey("TeacherID")]
    [InverseProperty("Courses")]
    public virtual Teacher Teacher { get; set; }
}
