// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace School_Management_System.Models;

[Table("Department")]
public partial class Department
{
    [Key]
    public int DepartmentID { get; set; }

    [StringLength(30)]
    public string Name { get; set; }

    [InverseProperty("Department")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    [InverseProperty("Department")]
    public virtual ICollection<Teacher> Teachers { get; set; } = new List<Teacher>();
}