// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace School_Management_System.Models;

[Table("Enrollment")]
public partial class Enrollment
{
    [Key]
    public int EnrollmentID { get; set; }

    public int? StudentID { get; set; }

    public int? CourseID { get; set; }

    public DateOnly? EnrollmentDate { get; set; }

    [ForeignKey("CourseID")]
    [InverseProperty("Enrollments")]
    public virtual Course Course { get; set; }

    [ForeignKey("StudentID")]
    [InverseProperty("Enrollments")]
    public virtual Student Student { get; set; }

   
}