// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace School_Management_System.Models;

[Table("Exam")]
public partial class Exam
{
    [Key]
    public int ExamID { get; set; }

    public int? CourseID { get; set; }

    [StringLength(30)]
    public string Type { get; set; }

    public double? Grade { get; set; }

    [ForeignKey("CourseID")]
    [InverseProperty("Exams")]
    public virtual Course Course { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<StudentExam> StudentExams { get; set; } = new List<StudentExam>();

    [InverseProperty("Exam")]
    public virtual ICollection<Teacher> Teachers { get; set; } = new List<Teacher>();
    public ICollection<Question> Questions { get; set; }

}