// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace School_Management_System.Models;

[Table("StudentExam")]
public partial class StudentExam
{
    [Key]
    public int StudentExamID { get; set; }

    public int? StudentID { get; set; }

    public int? ExamID { get; set; }

    public double? StudentGrade { get; set; }

    [ForeignKey("ExamID")]
    [InverseProperty("StudentExams")]
    public virtual Exam Exam { get; set; }

    [ForeignKey("StudentID")]
    [InverseProperty("StudentExams")]
    public virtual Student Student { get; set; }
}