// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace School_Management_System.Models;

[Table("Student")]
public partial class Student
{
    [Key]
    public int StudentID { get; set; }

    [Required]
    [StringLength(30)]
    public string Name { get; set; }

    public int? Age { get; set; }

    [StringLength(20)]
    public string Gender { get; set; }

    [StringLength(30)]
    public string Address { get; set; }

    [StringLength(30)]
    public string Phone { get; set; }

    public int? ClassID { get; set; }

    [ForeignKey("ClassID")]
    [InverseProperty("Students")]
    public virtual Class Class { get; set; }

    [InverseProperty("Student")]
    public virtual ICollection<Enrollment> Enrollments { get; set; } = new List<Enrollment>();

    [InverseProperty("Student")]
    public virtual ICollection<StudentExam> StudentExams { get; set; } = new List<StudentExam>();
}