// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace School_Management_System.Models;

[Table("Teacher")]
public partial class Teacher
{
    [Key]
    public int TeacherID { get; set; }

    [Required(ErrorMessage = "Teacher name is required")]
    [StringLength(30)]
    public string Name { get; set; }

    [Required]
    public DateOnly? HireDate { get; set; }
    [Required]
    public int? DepartmentID { get; set; }

    [Required(ErrorMessage = "Phone number is required")]
    [Phone]
    public string Phone { get; set; }

    [EmailAddress]
    public string Email { get; set; }

    public int? ExamID { get; set; }

    [Required]
    public string Role { get; set; }

    [InverseProperty("Teacher")]
    public virtual ICollection<Class> Classes { get; set; } = new List<Class>();

    [InverseProperty("Teacher")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    [ForeignKey("DepartmentID")]
    [InverseProperty("Teachers")]
    public virtual Department Department { get; set; }

    [ForeignKey("ExamID")]
    [InverseProperty("Teachers")]
    public virtual Exam Exam { get; set; }
}

